config/routes.rb
Rails.application.routes.draw do
  resources :reservations, :defaults => { :format => :json }
  mount_devise_token_auth_for 'User', at: 'auth', skip: [:omniauth_callbacks]#, controllers: { sessions: "overrides/sessions" }
  
  get '/users/:user_id/reservations', to: 'reservations#get_user_reservations', :defaults => {:format => :json}
  
  resources :parking_lots, :defaults => { :format => :json }
  resources :parking_spots, :defaults => { :format => :json } do 
    get '/reservations', to: 'reservations#get_parking_spot_reservations'
  end 

end

app/models/parking_lot.rb
class ParkingLot
  include Mongoid::Document
  field :name, type: String
  field :address, type: String
  field :city, type: String
  field :postal_code, type: String
  field :province, type: String
  field :country, type: String
  field :phone_number, type: String
end

app/controllers/parking_lots_controller.rb
class ParkingLotsController < ApplicationController
  before_action :set_parking_lot, only: [:show, :edit, :update, :destroy]

  # GET /parking_lots
  # GET /parking_lots.json
  def index
    @parking_lots = ParkingLot.all
  end

  # GET /parking_lots/1
  # GET /parking_lots/1.json
  def show
  end

  # GET /parking_lots/new
  def new
    @parking_lot = ParkingLot.new
  end

  # GET /parking_lots/1/edit
  def edit
  end

  # POST /parking_lots
  # POST /parking_lots.json
  def create
    @parking_lot = ParkingLot.new(parking_lot_params)

    respond_to do |format|
      if @parking_lot.save
        format.html { redirect_to @parking_lot, notice: 'Parking lot was successfully created.' }
        format.json { render :show, status: :created, location: @parking_lot }
      else
        format.html { render :new }
        format.json { render json: @parking_lot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parking_lots/1
  # PATCH/PUT /parking_lots/1.json
  def update
    respond_to do |format|
      if @parking_lot.update(parking_lot_params)
        format.html { redirect_to @parking_lot, notice: 'Parking lot was successfully updated.' }
        format.json { render :show, status: :ok, location: @parking_lot }
      else
        format.html { render :edit }
        format.json { render json: @parking_lot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parking_lots/1
  # DELETE /parking_lots/1.json
  def destroy
    @parking_lot.destroy
    respond_to do |format|
      format.html { redirect_to parking_lots_url, notice: 'Parking lot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parking_lot
      @parking_lot = ParkingLot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def parking_lot_params
      params.require(:parking_lot).permit(:name, :address, :city, :postal_code, :province, :country, :phone_number)
    end
end

app/helpers/parking_lots_helper.rb
module ParkingLotsHelper
end

app/views/parking_lots/_form.html.erb
<%= form_for(@parking_lot) do |f| %>
  <% if @parking_lot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@parking_lot.errors.count, "error") %> prohibited this parking_lot from being saved:</h2>

      <ul>
      <% @parking_lot.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :postal_code %><br>
    <%= f.text_field :postal_code %>
  </div>
  <div class="field">
    <%= f.label :province %><br>
    <%= f.text_field :province %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/parking_lots/edit.html.erb
<h1>Editing Parking Lot</h1>

<%= render 'form' %>

<%= link_to 'Show', @parking_lot %> |
<%= link_to 'Back', parking_lots_path %>

app/views/parking_lots/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Parking Lots</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>City</th>
      <th>Postal code</th>
      <th>Province</th>
      <th>Country</th>
      <th>Phone number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @parking_lots.each do |parking_lot| %>
      <tr>
        <td><%= parking_lot.name %></td>
        <td><%= parking_lot.address %></td>
        <td><%= parking_lot.city %></td>
        <td><%= parking_lot.postal_code %></td>
        <td><%= parking_lot.province %></td>
        <td><%= parking_lot.country %></td>
        <td><%= parking_lot.phone_number %></td>
        <td><%= link_to 'Show', parking_lot %></td>
        <td><%= link_to 'Edit', edit_parking_lot_path(parking_lot) %></td>
        <td><%= link_to 'Destroy', parking_lot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Parking lot', new_parking_lot_path %>

app/views/parking_lots/new.html.erb
<h1>New Parking Lot</h1>

<%= render 'form' %>

<%= link_to 'Back', parking_lots_path %>

app/views/parking_lots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @parking_lot.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @parking_lot.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @parking_lot.city %>
</p>

<p>
  <strong>Postal code:</strong>
  <%= @parking_lot.postal_code %>
</p>

<p>
  <strong>Province:</strong>
  <%= @parking_lot.province %>
</p>

<p>
  <strong>Country:</strong>
  <%= @parking_lot.country %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @parking_lot.phone_number %>
</p>

<%= link_to 'Edit', edit_parking_lot_path(@parking_lot) %> |
<%= link_to 'Back', parking_lots_path %>