config/routes.rb
Rails.application.routes.draw do
  resources :reservations, :defaults => { :format => :json }
  mount_devise_token_auth_for 'User', at: 'auth', skip: [:omniauth_callbacks]#, controllers: { sessions: "overrides/sessions" }
  
  get '/users/:user_id/reservations', to: 'reservations#get_user_reservations', :defaults => {:format => :json}
  
  resources :parking_lots, :defaults => { :format => :json }
  resources :parking_spots, :defaults => { :format => :json } do 
    get '/reservations', to: 'reservations#get_parking_spot_reservations'
  end 

end

app/models/parking_spot.rb
class ParkingSpot
  include Mongoid::Document
  validates_uniqueness_of :name
  has_many :reservations
  field :name, type: String
  field :occupied, type: Boolean
  field :reservable, type: Boolean
  field :reserved, type: Boolean
  
  before_update do
    
    ParkingSpot.all.each do |spot|
        @spot = spot if  self._id == spot._id
    end
    if @spot
      #raise Mongoid::Errors::Validations.new(self) if (self.reserved and @spot.reserved)
      #raise Mongoid::Errors::Validations.new(self) if (self.occupied and @spot.occupied)
      #raise Mongoid::Errors::Validations.new(self) if (self.reserved and not @spot.reservable)
    end
  end
end

app/controllers/parking_spots_controller.rb
class ParkingSpotsController < ApplicationController
  before_action :set_parking_spot, only: [:show, :edit, :update, :destroy]

  # GET /parking_spots
  # GET /parking_spots.json
  def index
    if params[:name]
      @parking_spots = ParkingSpot.where(name: params[:name])
    else
      @parking_spots = ParkingSpot.all
    end
  end

  # GET /parking_spots/1
  # GET /parking_spots/1.json
  def show
  end

  # GET /parking_spots/new
  def new
    @parking_spot = ParkingSpot.new
  end

  # GET /parking_spots/1/edit
  def edit
  end

  # POST /parking_spots
  # POST /parking_spots.json
  def create
    @parking_spot = ParkingSpot.new(parking_spot_params)

    respond_to do |format|
      if @parking_spot.save
        format.html { redirect_to @parking_spot, notice: 'Parking spot was successfully created.' }
        format.json { render :show, status: :created, location: @parking_spot }
      else
        format.html { render :new }
        format.json { render json: @parking_spot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parking_spots/1
  # PATCH/PUT /parking_spots/1.json
  def update
    respond_to do |format|
      if @parking_spot.update(parking_spot_params)
        format.html { redirect_to @parking_spot, notice: 'Parking spot was successfully updated.' }
        format.json { render :show, status: :ok, location: @parking_spot }
      else
        format.html { render :edit }
        format.json { render json: @parking_spot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parking_spots/1
  # DELETE /parking_spots/1.json
  def destroy
    @parking_spot.destroy
    respond_to do |format|
      format.html { redirect_to parking_spots_url, notice: 'Parking spot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parking_spot
      @parking_spot = ParkingSpot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def parking_spot_params
      params.permit(:name, :occupied, :reservable, :reserved)
    end
end

app/helpers/parking_spots_helper.rb
module ParkingSpotsHelper
end

app/views/parking_spots/_form.html.erb
<%= form_for(@parking_spot) do |f| %>
  <% if @parking_spot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@parking_spot.errors.count, "error") %> prohibited this parking_spot from being saved:</h2>

      <ul>
      <% @parking_spot.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :occupied %><br>
    <%= f.text_field :occupied %>
  </div>
  <div class="field">
    <%= f.label :reservable %><br>
    <%= f.text_field :reservable %>
  </div>
  <div class="field">
    <%= f.label :reserved %><br>
    <%= f.text_field :reserved %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/parking_spots/edit.html.erb
<h1>Editing Parking Spot</h1>

<%= render 'form' %>

<%= link_to 'Show', @parking_spot %> |
<%= link_to 'Back', parking_spots_path %>

app/views/parking_spots/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Parking Spots</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Occupied</th>
      <th>Reservable</th>
      <th>Reserved</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @parking_spots.each do |parking_spot| %>
      <tr>
        <td><%= parking_spot.name %></td>
        <td><%= parking_spot.occupied %></td>
        <td><%= parking_spot.reservable %></td>
        <td><%= parking_spot.reserved %></td>
        <td><%= link_to 'Show', parking_spot %></td>
        <td><%= link_to 'Edit', edit_parking_spot_path(parking_spot) %></td>
        <td><%= link_to 'Destroy', parking_spot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Parking spot', new_parking_spot_path %>

app/views/parking_spots/new.html.erb
<h1>New Parking Spot</h1>

<%= render 'form' %>

<%= link_to 'Back', parking_spots_path %>

app/views/parking_spots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @parking_spot.name %>
</p>

<p>
  <strong>Occupied:</strong>
  <%= @parking_spot.occupied %>
</p>

<p>
  <strong>Reservable:</strong>
  <%= @parking_spot.reservable %>
</p>

<p>
  <strong>Reserved:</strong>
  <%= @parking_spot.reserved %>
</p>

<%= link_to 'Edit', edit_parking_spot_path(@parking_spot) %> |
<%= link_to 'Back', parking_spots_path %>